import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import type { Prisma } from '@prisma/client';
import { withTenantScope } from '@/lib/orgContext';
import { seriesOccurrences } from '@/lib/meetingSeriesOccurrences';

// Stages that are terminal — an overdue deadline on these is not actionable.
const TERMINAL = ['HIRED_660', 'EMPLOYED_700', 'INTERNSHIP_FOUND_ELSEWHERE_800'];

const DAY_MS = 24 * 60 * 60 * 1000;
/** Widest window a single request may ask for, so month-hopping can't pull a decade. */
const MAX_RANGE_DAYS = 400;

// The window on screen. Omitting both bounds keeps the pre-#1110 contract —
// every stored event the caller can see, unfiltered — because API clients (and
// the deadline e2e, which plants a 2020 deadline) rely on it. A recurring rule
// still has to be expanded over *some* finite span, so it gets a default one.
function parseRange(url: URL) {
  const parse = (raw: string | null) => {
    if (!raw) return null;
    const d = new Date(raw);
    return Number.isNaN(d.getTime()) ? null : d;
  };
  const now = new Date();
  const from = parse(url.searchParams.get('from'));
  let to = parse(url.searchParams.get('to'));
  if (from && to && to < from) to = new Date(from.getTime() + DAY_MS);
  if (from && to && to.getTime() - from.getTime() > MAX_RANGE_DAYS * DAY_MS) {
    to = new Date(from.getTime() + MAX_RANGE_DAYS * DAY_MS);
  }
  return {
    from,
    to,
    seriesFrom: from ?? new Date(now.getTime() - 90 * DAY_MS),
    seriesTo: to ?? new Date(now.getTime() + 275 * DAY_MS),
  };
}

// GET ?from=&to= — calendar events visible to the caller, scoped by role, inside
// the requested window. Returns a flat list the month/week/day/agenda views bucket
// by day themselves.
export async function GET(request: Request) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  return await withTenantScope(session, async () => {
  const { id, role } = session.user;
  const { from, to, seriesFrom, seriesTo } = parseRange(new URL(request.url));
  // An absent bound means "no bound" — see parseRange.
  const inWindow = { ...(from ? { gte: from } : {}), ...(to ? { lte: to } : {}) };
  const relWhere: Prisma.MentorshipRelationWhereInput =
    role === 'ADMIN' ? {} : role === 'MENTOR' ? { mentorId: id } : { menteeId: id };

  const [meetings, relations, loggedMeetings, series] = await Promise.all([
    prisma.meeting.findMany({
      // `relationId: { not: null }` — since #1051 a meeting may instead hang off
      // a project or a conversation. Those are always time-less (instant rooms),
      // so they'd be dropped by the scheduledAt filter below anyway; excluding
      // them here keeps `relation` non-null for the mapping.
      //
      // `seriesId: null` — a recurring project meeting is rendered from its rule
      // (below), once per occurrence. Rows generated by the old materialising
      // series generator are the ghosts this excludes: one per mentee, stuck at
      // whatever time the rule used to have, surviving the series' cancellation
      // (#1110). Cancelling or moving a series now deletes them for good.
      where: { relationId: { not: null }, seriesId: null, scheduledAt: { not: null, ...inWindow }, relation: relWhere },
      include: { relation: { include: { mentee: { select: { fullName: true } } } } },
      orderBy: { scheduledAt: 'asc' },
    }),
    prisma.mentorshipRelation.findMany({
      where: { ...relWhere, stageDeadline: { not: null, ...inWindow } },
      include: { mentee: { select: { fullName: true } } },
    }),
    // Logged "Meeting" interactions are past meetings a mentor recorded without
    // going through the scheduling flow — surface them so the calendar isn't
    // empty when the team logs meetings as interactions instead.
    //
    // `meetingId: null` — a log written automatically from a scheduled meeting
    // (#1489) describes the row already listed above; without this the same
    // meeting would sit on the calendar twice. A log whose meeting was later
    // deleted has meetingId back to null (SetNull) and returns here, which is
    // right: it is then the only remaining record of that meeting.
    prisma.interactionLog.findMany({
      where: { type: 'Meeting', meetingId: null, ...(from || to ? { date: inWindow } : {}), relation: relWhere },
      include: { relation: { include: { mentee: { select: { fullName: true } } } } },
      orderBy: { date: 'asc' },
    }),
    // The recurring project meetings this user is expected at: every active rule
    // on a project they are a member of, or that one of their relations carries.
    prisma.meetingSeries.findMany({
      where: {
        active: true,
        projectId: { not: null },
        ...(role === 'ADMIN'
          ? {}
          : {
              project: {
                OR: [
                  { members: { some: { userId: id } } },
                  { relations: { some: { ...relWhere, status: 'ACTIVE' } } },
                ],
              },
            }),
      },
      select: {
        id: true,
        title: true,
        daysOfWeek: true,
        timeOfDay: true,
        timeZone: true,
        fixedLink: true,
        projectId: true,
        project: { select: { name: true } },
      },
    }),
  ]);

  const events = [
    // No-time meetings (nullable scheduledAt) don't belong on a calendar.
    ...meetings.filter((m) => m.scheduledAt && m.relation).map((m) => ({
      id: `meeting-${m.id}`,
      type: 'meeting' as const,
      title: m.title,
      who: m.relation!.mentee.fullName,
      date: m.scheduledAt!.toISOString(),
      link: m.meetLink ?? null,
    })),
    // One entry per occurrence of the rule — not one per attendee. The weekly
    // project call is a single event and shows its own title; the project name
    // is the context line, where a one-to-one meeting shows the mentee's name.
    ...series.flatMap((s) =>
      seriesOccurrences(s.daysOfWeek, s.timeOfDay, seriesFrom, seriesTo, s.timeZone).map((when) => ({
        id: `series-${s.id}-${when.toISOString()}`,
        type: 'series' as const,
        title: s.title,
        who: s.project?.name ?? s.title,
        date: when.toISOString(),
        link: s.fixedLink ?? null,
        projectId: s.projectId,
      }))
    ),
    ...loggedMeetings.map((i) => ({
      id: `logged-${i.id}`,
      type: 'logged' as const,
      title: i.notes.slice(0, 80) || 'Meeting',
      who: i.relation.mentee.fullName,
      date: i.date.toISOString(),
      link:
        role === 'ADMIN'
          ? `/admin/candidates/${i.relation.menteeId}`
          : role === 'MENTOR'
            ? `/mentor/mentees/${i.relationId}`
            : null,
    })),
    ...relations.map((r) => ({
      id: `deadline-${r.id}`,
      type: 'deadline' as const,
      title: r.pipelineStatus,
      who: r.mentee.fullName,
      date: r.stageDeadline!.toISOString(),
      overdue: r.stageDeadline! < new Date() && !TERMINAL.includes(r.pipelineStatus),
      // A mentee sees their own deadline but has no admin page to land on
      // (#915) — a dead /admin link would 403/redirect.
      link: role === 'MENTEE' ? '/portal/journey' : `/admin/candidates/${r.menteeId}`,
    })),
  ].sort((a, b) => a.date.localeCompare(b.date));

  return NextResponse.json({ events, from: from?.toISOString() ?? null, to: to?.toISOString() ?? null });
  });
}
