import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import type { Prisma } from '@prisma/client';
import { withTenantScope } from '@/lib/orgContext';
import { tenantWhere, withinTenant } from '@/lib/tenantFilter';
import { ruleOccurrences, SERIES_RULE_SELECT } from '@/lib/meetingSeriesOccurrences';
import { rangeEnd, rangeStart } from '@/lib/dateRange';
import { resolvePipelineStages } from '@/lib/pipelineStages';
import { resolveOrgId } from '@/lib/orgScope';
import { isStageOverdue } from '@/lib/stageClock';

const DAY_MS = 24 * 60 * 60 * 1000;
/** Widest window a single request may ask for, so month-hopping can't pull a decade. */
const MAX_RANGE_DAYS = 400;

// The window on screen. Omitting both bounds keeps the pre-#1110 contract —
// every stored event the caller can see, unfiltered — because API clients (and
// the deadline e2e, which plants a 2020 deadline) rely on it. A recurring rule
// still has to be expanded over *some* finite span, so it gets a default one.
function parseRange(url: URL) {
  const now = new Date();
  // A date-only bound names a whole day (#1501): a week view whose `to` is
  // Sunday has to include Sunday's events, not stop at Sunday 00:00.
  const from = rangeStart(url.searchParams.get('from'));
  let to = rangeEnd(url.searchParams.get('to'));
  if (from && to && to < from) to = new Date(from.getTime() + DAY_MS);
  if (from && to && to.getTime() - from.getTime() > MAX_RANGE_DAYS * DAY_MS) {
    to = new Date(from.getTime() + MAX_RANGE_DAYS * DAY_MS);
  }
  return {
    from,
    to,
    seriesFrom: from ?? new Date(now.getTime() - 90 * DAY_MS),
    seriesTo: to ?? new Date(now.getTime() + 275 * DAY_MS),
  };
}

// GET ?from=&to= — calendar events visible to the caller, scoped by role, inside
// the requested window. Returns a flat list the month/week/day/agenda views bucket
// by day themselves.
export async function GET(request: Request) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  return await withTenantScope(session, async () => {
  const { id, role } = session.user;
  const { from, to, seriesFrom, seriesTo } = parseRange(new URL(request.url));
  // An absent bound means "no bound" — see parseRange.
  const inWindow = { ...(from ? { gte: from } : {}), ...(to ? { lte: to } : {}) };
  // Every role's scope is narrowed to the caller's tenant (#2542 follow-up).
  // An ADMIN's used to be `{}` — with MT_ENFORCE_ISOLATION off that was every
  // tenant's meetings, deadlines and logged meetings, and every tenant's
  // recurring project calls through the series query below. Meeting,
  // InteractionLog and MeetingSeries carry no orgId: their tenant is the
  // relation's or the project's, which is where the filter goes.
  const tenant = await tenantWhere(session);
  const relWhere: Prisma.MentorshipRelationWhereInput = withinTenant<Prisma.MentorshipRelationWhereInput>(
    role === 'ADMIN' ? {} : role === 'MENTOR' ? { mentorId: id } : { menteeId: id },
    tenant,
  );
  const roleRelWhere: Prisma.MentorshipRelationWhereInput =
    role === 'ADMIN' ? {} : role === 'MENTOR' ? { mentorId: id } : { menteeId: id };

  // "Overdue" is the one stage-clock rule (#1724) fed the caller's tenant's own
  // stages (#1884), not three default keys a renamed pipeline does not have.
  const stages = await resolvePipelineStages(resolveOrgId(session));

  const [meetings, relations, loggedMeetings, series] = await Promise.all([
    prisma.meeting.findMany({
      // `relationId: { not: null }` — since #1051 a meeting may instead hang off
      // a project or a conversation. Those are always time-less (instant rooms),
      // so they'd be dropped by the scheduledAt filter below anyway; excluding
      // them here keeps `relation` non-null for the mapping.
      //
      // `seriesId: null` — a recurring project meeting is rendered from its rule
      // (below), once per occurrence. Rows generated by the old materialising
      // series generator are the ghosts this excludes: one per mentee, stuck at
      // whatever time the rule used to have, surviving the series' cancellation
      // (#1110). Cancelling or moving a series now deletes them for good.
      //
      // `status: 'SCHEDULED'` — a cancelled meeting (#1980) is off the calendar;
      // the row survives for its notes and its interaction log, not to keep
      // holding a slot nobody is coming to.
      where: {
        relationId: { not: null },
        seriesId: null,
        status: 'SCHEDULED',
        scheduledAt: { not: null, ...inWindow },
        relation: relWhere,
      },
      include: { relation: { include: { mentee: { select: { fullName: true } } } } },
      orderBy: { scheduledAt: 'asc' },
    }),
    prisma.mentorshipRelation.findMany({
      where: { ...relWhere, stageDeadline: { not: null, ...inWindow } },
      include: { mentee: { select: { fullName: true } } },
    }),
    // Logged "Meeting" interactions are past meetings a mentor recorded without
    // going through the scheduling flow — surface them so the calendar isn't
    // empty when the team logs meetings as interactions instead.
    //
    // `meetingId: null` — a log written automatically from a scheduled meeting
    // (#1489) describes the row already listed above; without this the same
    // meeting would sit on the calendar twice. A log whose meeting was later
    // deleted has meetingId back to null (SetNull) and returns here, which is
    // right: it is then the only remaining record of that meeting.
    prisma.interactionLog.findMany({
      where: { type: 'Meeting', meetingId: null, ...(from || to ? { date: inWindow } : {}), relation: relWhere },
      include: { relation: { include: { mentee: { select: { fullName: true } } } } },
      orderBy: { date: 'asc' },
    }),
    // The recurring project meetings this user is expected at: every active rule
    // on a project they are a member of, or that one of their relations carries.
    // A standing 1:1 (#2013) hangs off a relation instead: both of its
    // participants see it, scoped exactly like the relation's own meetings.
    prisma.meetingSeries.findMany({
      where: {
        active: true,
        OR: [
          {
            projectId: { not: null },
            project: {
              is: withinTenant<Prisma.ProjectWhereInput>(
                role === 'ADMIN'
                  ? {}
                  : {
                      OR: [
                        { members: { some: { userId: id } } },
                        { relations: { some: { ...roleRelWhere, status: 'ACTIVE' } } },
                      ],
                    },
                tenant,
              ),
            },
          },
          { relationId: { not: null }, relation: { is: relWhere } },
        ],
      },
      select: {
        id: true,
        title: true,
        ...SERIES_RULE_SELECT,
        fixedLink: true,
        projectId: true,
        relationId: true,
        project: { select: { name: true } },
        relation: { select: { mentee: { select: { fullName: true } }, mentor: { select: { fullName: true } } } },
      },
    }),
  ]);

  const events = [
    // No-time meetings (nullable scheduledAt) don't belong on a calendar.
    ...meetings.filter((m) => m.scheduledAt && m.relation).map((m) => ({
      id: `meeting-${m.id}`,
      type: 'meeting' as const,
      title: m.title,
      who: m.relation!.mentee.fullName,
      date: m.scheduledAt!.toISOString(),
      link: m.meetLink ?? null,
    })),
    // One entry per occurrence of the rule — not one per attendee. The weekly
    // project call is a single event and shows its own title; the project name
    // is the context line, where a one-to-one meeting shows the mentee's name.
    ...series.flatMap((s) =>
      ruleOccurrences(s, seriesFrom, seriesTo).map((when) => ({
        id: `series-${s.id}-${when.toISOString()}`,
        type: 'series' as const,
        title: s.title,
        // A standing 1:1 names the other participant, like a one-off meeting.
        who:
          s.project?.name ??
          (s.relation ? (role === 'MENTEE' ? s.relation.mentor.fullName : s.relation.mentee.fullName) : null) ??
          s.title,
        date: when.toISOString(),
        link: s.fixedLink ?? null,
        projectId: s.projectId,
      }))
    ),
    ...loggedMeetings.map((i) => ({
      id: `logged-${i.id}`,
      type: 'logged' as const,
      title: i.notes.slice(0, 80) || 'Meeting',
      who: i.relation.mentee.fullName,
      date: i.date.toISOString(),
      link:
        role === 'ADMIN'
          ? `/admin/candidates/${i.relation.menteeId}`
          : role === 'MENTOR'
            ? `/mentor/mentees/${i.relationId}`
            : null,
    })),
    ...relations.map((r) => ({
      id: `deadline-${r.id}`,
      type: 'deadline' as const,
      title: r.pipelineStatus,
      who: r.mentee.fullName,
      date: r.stageDeadline!.toISOString(),
      overdue: isStageOverdue({ stageDeadline: r.stageDeadline, pipelineStatus: r.pipelineStatus }, stages),
      // A mentee sees their own deadline but has no admin page to land on
      // (#915) — a dead /admin link would 403/redirect.
      link: role === 'MENTEE' ? '/portal/journey' : `/admin/candidates/${r.menteeId}`,
    })),
  ].sort((a, b) => a.date.localeCompare(b.date));

  return NextResponse.json({ events, from: from?.toISOString() ?? null, to: to?.toISOString() ?? null });
  });
}
